name: Publish to npm

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Extract tag version
      id: extract_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Extracted version: $VERSION"
    
    - name: Update package.json version
      run: |
        # Get current package.json version for logging
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        echo "Current version in package.json: $CURRENT_VERSION"
        
        # Update the version with the one from the tag
        npx --yes json -I -f package.json -e "this.version='${{ steps.extract_version.outputs.version }}'"
        
        # Verify the update
        NEW_VERSION=$(node -p "require('./package.json').version")
        echo "Updated version in package.json: $NEW_VERSION"
    
    - name: Build package
      run: npm run build
    
    - name: Set file permissions
      run: |
        chmod +x build/index.js
        echo "Set executable permissions on build/index.js"
    
    - name: Verify package contents
      run: |
        echo "Checking build directory..."
        ls -la build/
        echo "Checking that index.js has shebang line..."
        head -n 1 build/index.js
        echo "Creating a dry-run package..."
        npm pack --dry-run
    
    - name: Publish to npm
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}